// Demo data — 8 roofing operators in Houston, modeled after the real LongTail Scout output shape.
// Modeled to look realistic without inventing real businesses; names are fictional composites.
window.SCOUT_DATA = {
  query: "roofing contractors in Houston",
  niche: "roofing",
  city: "Houston",
  state: "TX",
  demand: {
    matching: 82431,
    total: 7142890,
    label: "roofing businesses in our index",
  },
  cost: {
    bd_renders: 27,
    llm_calls: 4,
    llm_input_tokens: 18420,
    llm_output_tokens: 3140,
    bd_usd: 0.0648,
    llm_usd: 0.0061,
    total_usd: 0.0709,
  },
  phases: [
    { id: "discovery", label: "Discovery", blurb: "Bright Data SERPs — 4 parallel queries", events: 18 },
    { id: "enrichment", label: "Enrichment", blurb: "Per-candidate homepage + careers + news", events: 41 },
    { id: "synthesis", label: "Synthesis", blurb: "Rank + ICP fit + sales angle, with citations", events: 9 },
  ],
  trace: [
    { ev: "phase",    text: "▶ discovery — SERP queries via Bright Data Scraping Browser" },
    { ev: "tool",     text: "→ bridge.serp({\"q\":\"roofing contractors houston tx\",\"n\":20})" },
    { ev: "tool",     text: "→ bridge.serp({\"q\":\"residential roof replacement houston\",\"n\":20})" },
    { ev: "tool",     text: "→ bridge.serp({\"q\":\"storm damage roofers houston small business\",\"n\":20})" },
    { ev: "tool",     text: "→ bridge.serp({\"q\":\"commercial roofing contractor houston\",\"n\":20})" },
    { ev: "progress", text: "· 80 SERP hits → 34 unique hostnames → 12 passing long-tail filter" },
    { ev: "phase",    text: "▶ enrichment — per-candidate homepage render" },
    { ev: "tool",     text: "→ bridge.render(bayouroof.co/about) [BD browser, 1.2s]" },
    { ev: "enrich",   text: "  ✓ bayouroof.co — about, hiring, geocode" },
    { ev: "tool",     text: "→ bridge.render(texanroof-houston.com/careers) [BD browser, 1.4s]" },
    { ev: "enrich",   text: "  ✓ texanroof-houston.com — 4 open roles (Lever ATS)" },
    { ev: "tool",     text: "→ bridge.render(heightsroofingtx.com) [BD browser, 0.9s]" },
    { ev: "enrich",   text: "  ✓ heightsroofingtx.com — about, recent news x2" },
    { ev: "tool",     text: "→ bridge.render(gulfcoastroofco.com/jobs) [BD browser, 1.1s]" },
    { ev: "enrich",   text: "  ✓ gulfcoastroofco.com — 6 open roles (Greenhouse ATS)" },
    { ev: "progress", text: "· enrichment complete — 12 candidates, 41 BD renders, $0.0648" },
    { ev: "phase",    text: "▶ synthesis — rank + ICP fit + draft outreach" },
    { ev: "progress", text: "· LLM rank: 8 operators above confidence threshold" },
    { ev: "progress", text: "· cross-niche memory: 2 also surfaced under \"storm-damage repair Texas\"" },
    { ev: "done",     text: "✓ complete — 8 operators, 27 BD renders, $0.0709 total" },
  ],
  operators: [
    {
      rank: 1,
      confidence: 92,
      name: "Bayou Roofing Co.",
      url: "bayouroof.co",
      domain: "bayouroof.co",
      hostnameMatch: true,
      size_estimate: "11-50",
      city: "Houston, TX",
      neighborhood: "Heights",
      founded: 2014,
      about: "Independently-owned roofing contractor serving Houston's inner loop. Crews specialize in storm-damage restoration and metal-roof retrofits on 1920s bungalows.",
      icp_fit_reason: "Mid-size, owner-operator, growing crew. Exactly the AccuLynx ICP — too big for QuickBooks, too small for ServiceTitan Enterprise.",
      sales_angle: "Heights bungalows + storm-damage spike = manual estimate hell. AccuLynx's drone-measure flow cuts that per-job 3x.",
      hiring: { count: 5, roles: ["Roofing crew lead", "Estimator", "Office coordinator"], source: "bayouroof.co/careers", ats: "Greenhouse" },
      recent_activity: [
        { headline: "Hurricane Beryl response: 240 storm jobs in 60 days", source: "chron.com/business/2024/08/bayou-roofing-beryl", date: "2024-08-12" },
        { headline: "Bayou Roofing named Heights Chamber 'Trade of the Year'", source: "houstonheights.org/awards-2024", date: "2024-11-03" },
      ],
      sources: [
        { field: "about",          tool: "BD browser → bayouroof.co/about" },
        { field: "hiring",         tool: "BD browser → bayouroof.co/careers" },
        { field: "size",           tool: "BD browser → bayouroof.co/team" },
        { field: "recent_activity",tool: "BD SERP → chron.com" },
        { field: "geocode",        tool: "Nominatim — 4317 N Main St, Houston TX" },
      ],
      geo: { lat: 29.7867, lng: -95.3793 },
      memory: { state: "new", seen: 1 },
      apolloThin: true,
    },
    {
      rank: 2,
      confidence: 89,
      name: "Texan Roof & Renovation",
      url: "texanroof-houston.com",
      domain: "texanroof-houston.com",
      hostnameMatch: true,
      size_estimate: "11-50",
      city: "Houston, TX",
      neighborhood: "Energy Corridor",
      founded: 2009,
      about: "Family-run roofing + light-renovation outfit. Strong word-of-mouth in West Houston master-planned neighborhoods; 4.9★ across 600+ Google reviews.",
      icp_fit_reason: "Hiring 4 roles via Lever — actively scaling. Reviews + tenure indicate $5M-15M revenue band.",
      sales_angle: "You're hiring an Operations Manager and 2 Estimators. JobNimbus's CRM scales the office work without adding a person.",
      hiring: { count: 4, roles: ["Operations Manager", "Estimator (x2)", "Crew Foreman"], source: "jobs.lever.co/texanroof", ats: "Lever" },
      recent_activity: [
        { headline: "Texan Roof opens 2nd yard in Katy", source: "houstonchronicle.com/business/2025/03/texan-roof-katy", date: "2025-03-19" },
      ],
      sources: [
        { field: "about",          tool: "BD browser → texanroof-houston.com" },
        { field: "hiring",         tool: "BD browser → jobs.lever.co/texanroof" },
        { field: "size",           tool: "BD browser → reviews aggregate" },
        { field: "recent_activity",tool: "BD SERP → houstonchronicle.com" },
        { field: "geocode",        tool: "Nominatim — 14201 Memorial Dr, Houston TX" },
      ],
      geo: { lat: 29.7754, lng: -95.5601 },
      memory: { state: "frequent", seen: 4, cross_niche: ["storm-damage repair Texas"] },
      apolloThin: true,
    },
    {
      rank: 3,
      confidence: 86,
      name: "Heights Roofing & Restoration",
      url: "heightsroofingtx.com",
      domain: "heightsroofingtx.com",
      hostnameMatch: true,
      size_estimate: "11-50",
      city: "Houston, TX",
      neighborhood: "Heights",
      founded: 2017,
      about: "Roofing + historical-restoration specialist. The go-to for Heights/Montrose homes on the historical registry that need code-compliant cedar-shake retrofits.",
      icp_fit_reason: "Niche-of-niche: historical-restoration roofing. Tight ICP for Roofr's estimate tool — every job is custom-measured.",
      sales_angle: "Historical Heights jobs need 3-5 measurement revisions per estimate. Roofr's satellite + manual hybrid kills that round-trip.",
      hiring: { count: 2, roles: ["Restoration Lead", "Junior Estimator"], source: "heightsroofingtx.com/careers", ats: "On-site form" },
      recent_activity: [
        { headline: "Heights Roofing wins Preservation Houston restoration award", source: "preservationhouston.org/2025-awards", date: "2025-02-08" },
        { headline: "Featured in Houstonia: 'The crew restoring 1920s Heights bungalows'", source: "houstoniamag.com/heights-roofing-feature", date: "2024-12-14" },
      ],
      sources: [
        { field: "about",          tool: "BD browser → heightsroofingtx.com" },
        { field: "hiring",         tool: "BD browser → heightsroofingtx.com/careers" },
        { field: "recent_activity",tool: "BD SERP → preservationhouston.org" },
        { field: "geocode",        tool: "Nominatim — 1218 W 19th St, Houston TX" },
      ],
      geo: { lat: 29.8024, lng: -95.4116 },
      memory: { state: "new", seen: 1 },
      apolloThin: true,
    },
    {
      rank: 4,
      confidence: 84,
      name: "Gulf Coast Roofers",
      url: "gulfcoastroofco.com",
      domain: "gulfcoastroofco.com",
      hostnameMatch: true,
      size_estimate: "51-100",
      city: "Houston, TX",
      neighborhood: "Clear Lake",
      founded: 2003,
      about: "Commercial-leaning roofer with 6 open roles on Greenhouse — strongest hiring signal in the dataset. Mix of residential storm work and commercial flat-roof contracts.",
      icp_fit_reason: "Open Greenhouse → ATS-rendered JS is exactly the BD Browser API use case. 6 roles = serious 2025 build-out.",
      sales_angle: "Six open roles via Greenhouse means an ops bottleneck. ServiceTitan's commercial module handles flat-roof + residential under one roof.",
      hiring: { count: 6, roles: ["Sales (x2)", "Estimator", "Commercial PM", "Foreman", "Office Mgr"], source: "boards.greenhouse.io/gulfcoastroof", ats: "Greenhouse" },
      recent_activity: [
        { headline: "Gulf Coast wins NASA Johnson Space Center re-roofing contract", source: "bizjournals.com/houston/2025/01/gulf-coast-nasa", date: "2025-01-22" },
      ],
      sources: [
        { field: "about",          tool: "BD browser → gulfcoastroofco.com" },
        { field: "hiring",         tool: "BD browser → boards.greenhouse.io/gulfcoastroof" },
        { field: "size",           tool: "BD browser → gulfcoastroofco.com/team" },
        { field: "recent_activity",tool: "BD SERP → bizjournals.com" },
        { field: "geocode",        tool: "Nominatim — 2811 NASA Pkwy, Houston TX" },
      ],
      geo: { lat: 29.5519, lng: -95.0978 },
      memory: { state: "familiar", seen: 2 },
      apolloThin: true,
    },
    {
      rank: 5,
      confidence: 78,
      name: "Lone Star Pro Roofing",
      url: "lonestarproroof.com",
      domain: "lonestarproroof.com",
      hostnameMatch: true,
      size_estimate: "11-50",
      city: "Houston, TX",
      neighborhood: "Spring Branch",
      founded: 2011,
      about: "Residential storm-restoration shop. Heavy on insurance-claim work. Active on LinkedIn but no company page — owner-only.",
      icp_fit_reason: "Insurance-claim heavy shops are JobNimbus's sweetest spot — claim-tracking is their differentiator.",
      sales_angle: "Insurance-claim docs are 60% of your admin time. JobNimbus's claim module + Xactimate sync is the unlock.",
      hiring: { count: 1, roles: ["Insurance Claims Specialist"], source: "indeed.com/cmp/lone-star-pro", ats: "Indeed" },
      recent_activity: [],
      sources: [
        { field: "about",          tool: "BD browser → lonestarproroof.com" },
        { field: "hiring",         tool: "BD SERP → indeed.com" },
        { field: "geocode",        tool: "Nominatim — 8200 Long Point Rd, Houston TX" },
      ],
      geo: { lat: 29.8050, lng: -95.5180 },
      memory: { state: "new", seen: 1 },
      apolloThin: true,
    },
    {
      rank: 6,
      confidence: 74,
      name: "Crescent Roofing TX",
      url: "crescentrooftx.com",
      domain: "crescentrooftx.com",
      hostnameMatch: true,
      size_estimate: "11-50",
      city: "Houston, TX",
      neighborhood: "Sugar Land",
      founded: 2016,
      about: "Sugar Land–based residential roofer. Lean crew, premium positioning, partnered with two solar installers.",
      icp_fit_reason: "Solar-partnership angle = ICP for energy-conscious roofing CRMs (Roofr, JobNimbus solar module).",
      sales_angle: "Your solar-roof co-marketing with two installers needs joint project tracking. Roofr's solar add-on solves the hand-off.",
      hiring: { count: 1, roles: ["Sales Estimator"], source: "crescentrooftx.com/join", ats: "On-site form" },
      recent_activity: [
        { headline: "Crescent partners with SunBright Solar for tile+panel installs", source: "sugarlandbiz.com/crescent-sunbright", date: "2024-10-30" },
      ],
      sources: [
        { field: "about",          tool: "BD browser → crescentrooftx.com" },
        { field: "hiring",         tool: "BD browser → crescentrooftx.com/join" },
        { field: "recent_activity",tool: "BD SERP → sugarlandbiz.com" },
        { field: "geocode",        tool: "Nominatim — 13909 SW Fwy, Sugar Land TX" },
      ],
      geo: { lat: 29.6196, lng: -95.6349 },
      memory: { state: "new", seen: 1 },
      apolloThin: true,
    },
    {
      rank: 7,
      confidence: 71,
      name: "Magnolia Roofing Houston",
      url: "magnoliaroofhouston.com",
      domain: "magnoliaroofhouston.com",
      hostnameMatch: true,
      size_estimate: "1-10",
      city: "Houston, TX",
      neighborhood: "Pearland",
      founded: 2019,
      about: "Small, fast-growing residential crew in south Houston. No web presence beyond their site — perfectly Apollo-thin.",
      icp_fit_reason: "Under-10-employee crew with their own site = exact long-tail wedge example. Apollo has zero contacts here.",
      sales_angle: "You're at the size where the next hire either drowns or doubles output. A starter-tier roofing CRM is the inflection.",
      hiring: { count: 1, roles: ["Roofing Crew Member"], source: "magnoliaroofhouston.com/work-with-us", ats: "On-site form" },
      recent_activity: [],
      sources: [
        { field: "about",          tool: "BD browser → magnoliaroofhouston.com" },
        { field: "hiring",         tool: "BD browser → magnoliaroofhouston.com/work-with-us" },
        { field: "geocode",        tool: "Nominatim — 2602 Smith Ranch Rd, Pearland TX" },
      ],
      geo: { lat: 29.5636, lng: -95.2860 },
      memory: { state: "new", seen: 1 },
      apolloThin: true,
    },
    {
      rank: 8,
      confidence: 68,
      name: "Houston Roof Pros",
      url: "houstonroofpros.net",
      domain: "houstonroofpros.net",
      hostnameMatch: true,
      size_estimate: "11-50",
      city: "Houston, TX",
      neighborhood: "Cypress",
      founded: 2008,
      about: "Cypress-area residential + light-commercial roofer. Steady, no obvious growth phase, but reviews + tenure indicate stable mid-market business.",
      icp_fit_reason: "Stable mid-market roofer = upgrade-cycle ICP, not growth-stage. AccuLynx's mature-business pitch.",
      sales_angle: "Steady book + 17 years in. The next 3 years is about margin, not growth — AccuLynx's job-costing reports are the lever.",
      hiring: { count: 0, roles: [], source: null, ats: null },
      recent_activity: [],
      sources: [
        { field: "about",          tool: "BD browser → houstonroofpros.net" },
        { field: "geocode",        tool: "Nominatim — 13634 Spring Cypress Rd, Cypress TX" },
      ],
      geo: { lat: 29.9690, lng: -95.6890 },
      memory: { state: "familiar", seen: 3 },
      apolloThin: true,
    },
  ],
  // Apollo counterfactual — what a vertical SDR would actually pull from Apollo for the same query.
  apolloPicks: [
    { name: "Beacon Roofing Supply", hint: "National distributor, 500+ employees — not an installer.", reason: "wrong-segment" },
    { name: "GAF Materials Corp.", hint: "Manufacturer. SDR target only at the corp level.", reason: "wrong-segment" },
    { name: "Owens Corning", hint: "Public manufacturer. Not in market for roofing-CRM.", reason: "wrong-segment" },
    { name: "Power Home Remodeling", hint: "National franchise, 2,800 emp. Already on AccuLynx Enterprise.", reason: "saturated" },
    { name: "Allen Roofing (LinkedIn only)", hint: "Profile dormant since 2019. Almost certainly out of business.", reason: "stale" },
    { name: "Houston Roofing Group Inc.", hint: "Aggregator/lead-gen — not the operator.", reason: "aggregator" },
  ],
  demandIndex: {
    // For heat-map dots (lat, lng, count, rating)
    points: [
      [29.7604, -95.3698, 18, 4.2],
      [29.7867, -95.3793, 24, 4.7],
      [29.8024, -95.4116, 15, 4.5],
      [29.7754, -95.5601, 31, 4.4],
      [29.5519, -95.0978, 22, 4.1],
      [29.5636, -95.2860,  9, 4.6],
      [29.9690, -95.6890, 14, 4.0],
      [29.6196, -95.6349, 11, 4.3],
      [29.7000, -95.4500, 19, 4.2],
      [29.6500, -95.3500, 12, 3.9],
      [29.8500, -95.4500,  8, 4.4],
      [29.7200, -95.6200, 16, 4.3],
      [29.6800, -95.2200, 13, 4.1],
      [29.7900, -95.5200,  7, 4.5],
      [29.9100, -95.5400, 21, 4.0],
      [29.6300, -95.5800, 10, 4.2],
      [29.5900, -95.3000,  6, 4.6],
      [29.7700, -95.7100, 14, 4.1],
      [29.7400, -95.3000, 17, 4.4],
      [29.8200, -95.2500,  9, 4.3],
    ],
  },
};
