/**
 * Account-brief Markdown builder — the pure half of v1.4.0.
 *
 * Renders a one-page, paste-anywhere Markdown dossier for a single operator: who they are, why
 * they fit, the evidence (hiring / recent activity / tech stack / LinkedIn-absence), discovered
 * contacts, a draft email, and the numbered Bright Data sources behind every claim. Pure string
 * formatting — the handler just provides the operator + any freshly-discovered extras.
 */
import type { Operator } from "../types";

export interface BriefExtras {
  contacts?: {
    emails?: { email: string; same_domain: boolean }[];
    phone?: string | null;
    contact?: { name: string; role: string } | null;
  } | null;
  linkedin?: { on_linkedin: boolean; evidence_url?: string | null } | null;
  email?: { subject: string; body: string } | null;
}

function hostOf(url: string): string {
  try { return new URL(url).hostname.replace(/^www\./, ""); } catch { return url; }
}

export function briefFilename(op: Operator): string {
  const slug = (op.name || hostOf(op.url) || "operator")
    .toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 60) || "operator";
  return `longtail-brief-${slug}.md`;
}

export function buildAccountBrief(op: Operator, extras: BriefExtras = {}): string {
  const L: string[] = [];
  const meta = [hostOf(op.url), op.size_estimate ? `${op.size_estimate} emp` : "", op.city || ""]
    .filter(Boolean).join(" · ");

  L.push(`# ${op.name}`);
  if (meta) L.push(meta);
  L.push("");
  L.push(`> Confidence ${op.confidence}/100 · Rank #${op.rank}`);
  L.push("");

  if (op.about) {
    L.push("## About");
    L.push(op.about);
    L.push("");
  }

  L.push("## Why they fit");
  L.push(op.icp_fit_reason || "—");
  L.push("");

  L.push("## Outreach angle");
  L.push(`*${op.sales_angle || "—"}*`);
  L.push("");

  // Signals
  const signals: string[] = [];
  if ((op.hiring?.count ?? 0) > 0) {
    const roles = (op.hiring.roles ?? []).slice(0, 6).join(", ");
    signals.push(`**Hiring:** ${op.hiring.count} open role${op.hiring.count === 1 ? "" : "s"}${roles ? ` — ${roles}` : ""}${op.hiring.source ? ` ([careers](${op.hiring.source}))` : ""}`);
  }
  for (const a of op.recent_activity ?? []) {
    if (!a.headline) continue;
    signals.push(`**Recent:** ${a.headline}${a.date ? ` (${a.date})` : ""}${a.source ? ` ([source](${a.source}))` : ""}`);
  }
  if (op.tech_stack && op.tech_stack.length > 0) {
    signals.push(`**Tech stack:** ${op.tech_stack.join(", ")}`);
  }
  const li = extras.linkedin;
  if (li) {
    signals.push(li.on_linkedin
      ? `**LinkedIn:** listed on LinkedIn${li.evidence_url ? ` — ${li.evidence_url}` : ""} (Apollo can likely enrich — weaker long-tail signal)`
      : `**LinkedIn:** Not on LinkedIn — confirmed via Bright Data. Invisible to Apollo/ZoomInfo/Clay; found via their own website.`);
  }
  if (signals.length > 0) {
    L.push("## Signals");
    for (const s of signals) L.push(`- ${s}`);
    L.push("");
  }

  // Contacts — prefer freshly-discovered extras, fall back to what enrichment found.
  const emails = extras.contacts?.emails ?? [];
  const phone = extras.contacts?.phone ?? op.phone ?? null;
  const person = extras.contacts?.contact ?? op.contact ?? null;
  if (emails.length > 0 || phone || person) {
    L.push("## Contact");
    for (const e of emails) L.push(`- Email: ${e.email}${e.same_domain ? " (own domain)" : ""}`);
    if (phone) L.push(`- Phone: ${phone}`);
    if (person) L.push(`- Contact: ${person.name} — ${person.role}`);
    L.push("");
  }

  // Draft email
  if (extras.email?.subject || extras.email?.body) {
    L.push("## Draft email");
    L.push(`**Subject:** ${extras.email.subject ?? ""}`);
    L.push("");
    L.push(extras.email.body ?? "");
    L.push("");
  }

  // Sources
  const sources = op.sources ?? [];
  L.push(`## Sources · ${sources.length} Bright Data fetch${sources.length === 1 ? "" : "es"}`);
  if (sources.length === 0) {
    L.push("_(none recorded)_");
  } else {
    sources.forEach((s, i) => L.push(`${i + 1}. **${s.field}** — [${s.tool}](${s.url})`));
  }
  L.push("");

  L.push("---");
  L.push(`Generated by LongTail Scout · built on Bright Data · ${op.url}`);

  return L.join("\n");
}
