name = "longtail-scout"
main = "src/index.ts"
compatibility_date = "2026-05-27"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "longtailscout.com", custom_domain = true },
  { pattern = "www.longtailscout.com", custom_domain = true }
]

[assets]
directory = "../web/dist"
binding = "ASSETS"

[[kv_namespaces]]
binding = "CACHE"
id = "64e28df0a8b64be9bad2f5a390aab1a0"
preview_id = "44076d76467b4abe807c3c82cf7aea50"
